---
- name: Installing docker
  hosts: docker
  become: yes
  tasks:
    - name: Install dependencies
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
    - name: Import docker key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add docker repository to system
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

    - name: Install docker 
      package:
        name: "{{item}}"
        state: present
      with_items:
         - docker-ce
         - docker-ce-cli
         - containerd.io        
         - docker-compose
