---
- hosts: tomcat
  become: yes
  vars:
  - https_port: 8090
  tasks:
    - name: add group "tomcat"
      group: 
         name: tomcat

    - name: add user "tomcat"
      user: 
         name: tomcat 
         group: tomcat 
         createhome: yes
      become: true
    - name: Download tomcat
      get_url:
         url: http://archive.apache.org/dist/tomcat/tomcat-8/v8.5.16/bin/apache-tomcat-8.5.16.tar.gz
         dest: /home/ravi07/apache-tomcat-8.5.16.tar.gz

    - name: Extract Tomcat archive
      unarchive:
         src: /home/ravi07/apache-tomcat-8.5.16.tar.gz
         dest: /opt
         remote_src: yes     
    - name: Change ownership of Tomcat installation
      file: 
         path: /opt/apache-tomcat-8.5.16 
         owner: tomcat
         group: tomcat 
         state: directory 
         recurse: yes

    - name: Configure Tomcat server
      template: 
         src: server.xml 
         dest: /opt/apache-tomcat-8.5.16/conf/

    - name: Configure Tomcat users
      template:
         src: tomcat-users.xml 
         dest: /opt/apache-tomcat-8.5.16/conf/


    - name: Start Tomcat
      command: nohup /opt/apache-tomcat-8.5.16/bin/startup.sh
      become: true
      become_user: tomcat
